###服务端口号
server:
  port: 8001
spring:
  application:
    name: black-shop-basic-apollo
###eureka 基本信息配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
   